version: '3'


services:
  web:
    build:
      context: ./
    ports:
      - "8080:80"
  my-sql:
    build:
      dockerfile: Mysql.Dockerfile
      context: ./
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'weak_user'
      MYSQL_PASSWORD: 'weak_password'
      MYSQL_ROOT_PASSWORD: 'weak_root_password'